### ISSUE TITLE
failed to import bridging header

### ISSUE THREAD

**Issue by muratyilmaz** [yshrkt/VuforiaSampleSwift#3]
Hi, 

i always get error "failed to import bridging header".
Any idea?

**/Users/muratyilmaz/Desktop/VuforiaSampleSwift-# master/VuforiaSampleSwift/VuforiaManager/VuforiaEAGLView.h:11:9: 'Vuforia/UIGLViewProtocol.h' file not found

Failed to import bridging header '/Users/muratyilmaz/Desktop/VuforiaSampleSwift-master/VuforiaSampleSwift-Bridging-Header.h'**

**Comment by muratyilmaz** [comment]
Problem solved. thanks for your work. its very useful. i have one more question.  Does it support Vuforia Object Rego?

**Comment by yshrkt** [comment]
Thank you for your question.
I didn't try Object Rego. But, as far as I read Vuforia's sample code, I think that my sample maybe work with Object Rego.

**Comment by muratyilmaz** [comment]
I'll try Object Rego today. I'll give feedback about it.

**Comment by yshrkt** [comment]
Thanks.
If you got some problem, please tell me about it.

**Comment by Silvering** [comment]
Hi muratyilmaz. I have exactly the same problem. How did you solve it ?

**Comment by muratyilmaz** [comment]
Hi Silvering,
i was trying to run on simulator :) This is the problem. Vuforia doesn't work on simulator.
first you must plug your iPhone and select your iPhone on Xcode.

**Comment by Silvering** [comment]
I just solved the problem which was the header.h import. Thanks for your reactivity ;-)

**Comment by AmonDeng** [comment]
@Silvering Hi Silvering ,I also have the same problem ,can you tell me how to solve .i almost crazy
i always get error "failed to import bridging header".

**Comment by yshrkt** [comment]
@AmonDeng 
I fixed the bridging header path for Release configuration. 
If you try to build using Release configuration, please try it after applying this fix.
Otherwise, please check the below.
* Vuforia SDK doesn't work simulator, You must use iOS Device.
* You need to copy Vuforia SDK into This Project.
* Please check that `Header Search Paths` and `Objective-Bridging Header` in Build Settings of VuforiaSampleSwift target are correct.

**Comment by AmonDeng** [comment]
@yshrkt  still not work ,it appear a new problem ." vuforia file not found"  but I did include libVuforia.a
this problem make me lost much Hair

**Comment by AmonDeng** [comment]
@yshrkt  can you send a whole project to my email AmonDeng@163.com .  I'm desperate to solve this problem and know how to combine scene kit and vuforia. 
Good people good life!

**Comment by markleeyw** [comment]
I tried to change bridging header to latest 6.x Vuforia SDK but had lots of errors. So  I had to rename Vuforia latest SDK to the old 5.5 one then it works.  Also when apps loads it says scenekit context not found ... it can detect the target but shows a almost transparent red box . Maybe I am doing something wrong. Any advise?

**Comment by MinaAshena** [comment]
I have the same problem.
I've changed the `header search path ` like this: `$(SRCROOT)/VuforiaSampleSwift/vuforia-sdk-ios-6-2-9/build/include/Vuforia` and the `Objective-Bridging Header` like this: `$(SRCROOT)/VuforiaSampleSwift/VuforiaSampleSwift-Bridging-Header.h` and i still get error.
`Vuforia/UIGLViewProtocol.h' file not found` and `Failed to import bridging header ‘/(rootPath/VuforiaSampleSwift/VuforiaSampleSwift/VuforiaSampleSwift-Bridging-Header.h`.
does any one know how to fix this?

**Comment by praveenfav** [comment]
I also encounter the same problem like @MinaAshena and how did you resolve the issue @muratyilmaz

**Comment by leeprobert** [comment]
The issue is in the headers that reference <Vuforia/**.h> do not know how to resolve the <Vuforia/> framework name. If these do not compile then the bridging header fails.

#import <Vuforia/UIGLViewProtocol.h> is the first point of failure. This is in VuforiaEAGLView.

**Comment by yshrkt** [comment]
1. Copy Vuforia SDK to `$(PROJECT_DIR)/VuforiaSampleSwift/vuforia-sdk-ios-6-2-9`.
2. Copy Vuforia Image Targets to `$(PROJECT_DIR)/VuforiaSampleSwift/VuforiaAssets/ImageTargets`.
   e.g. `VuforiaSamples-6-2-11/VuforiaSamples/Resources/Assets/ImageTargets`
3. Reopen VuforiaSampleSwift.xcodeproj 
4. Changes build settings as bellow if needed:
  
    | | |
    |--|--|
    |Hear Search Paths|`"$(SRCROOT)/VuforiaSampleSwift/vuforia-sdk-ios-6-2-9/build/include"`|
    |Library Search Paths|`$(PROJECT_DIR)/VuforiaSampleSwift/vuforia-sdk-ios-6-2-9/build/lib/arm`|
    |Objective-Bridging Header|`VuforiaSampleSwift/VuforiaSampleSwift-Bridging-Header.h`|

**Comment by DixPatel009** [comment]
I have the same problem.

**Error :** 

/Users/apple/Downloads/VuforiaSampleSwift-master/VuforiaSampleSwift/VuforiaManager/VuforiaEAGLView.h:11:9: **error: could not build module 'Vuforia'
#import <Vuforia/UIGLViewProtocol.h>**

<unknown>:0: **error: failed to emit precompiled header** '/Users/apple/Library/Developer/Xcode/DerivedData/VuforiaSampleSwift-dvryxxfoldtndabwrtwxhvibvpbm/Build/Intermediates.noindex/PrecompiledHeaders/VuforiaSampleSwift-Bridging-Header-swift_1224YBKGJ1X1-clang_18DCYIGZG1FMG.pch' for bridging header '/Users/apple/Downloads/VuforiaSampleSwift-master/VuforiaSampleSwift/VuforiaSampleSwift-Bridging-Header.h'


i Set all setting as per comment.
I am Using **vuforia-sdk-ios-8-5-8** latest version **link** : [https://developer.vuforia.com/downloads/sdk](url)
i am also copy Image Targets in my project from vuforia sample project **link** : [https://developer.vuforia.com/downloads/samples](url)

**1) Header Path :**  $(SRCROOT)/VuforiaSampleSwift/vuforia-sdk-ios-8-5-8/build/include
**2) Search Path :** $(PROJECT_DIR)/VuforiaSampleSwift/vuforia-sdk-ios-8-5-8/build/lib/arm
**3) Objective-Bridging Header :** VuforiaSampleSwift/VuforiaSampleSwift-Bridging-Header.h 

Please let me know if any thing missing.
